version: 1
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world
  - name: dev
    jobs:
      - world
      - hello
      - hello-world
    when:
      and:
        - equal:
            - << status.build.hello >>
            - success
        - equal:
            - << status.build.hello-world >>
            - failed
pipeline-when:
  equal:
    - << status.build >>
    - success