version: 1
jobs:
  catalyst-cli-setup:
    steps:
      - echo "install Start"
      - npm install -g zcatalyst-cli
      - echo "Installed zcatalyst-cli"
      - catalyst --version
      - echo "Deploying"
      - catalyst deploy --only functions
      - echo "Deployed"
stages:
  - name: build
    jobs:
      - catalyst-cli-setup
