version: 1
jobs:
  catalyst-cli-setup:
    steps:
      - echo "Its working"
      - npm install -g zcatalyst-cli
      - echo "Installed zcatalyst-cli"
      - catalyst --version
      - echo "Deploying"
      - catalyst deploy
      - echo "Deployed"
stages:
  - name: build
    jobs:
      - catalyst-cli-setup
