version: 1.0
jobs:
  catalyst-cli-setup:
    steps:
      - echo "install Start"
      - npm install -g zcatalyst-cli
      - echo "Installed zcatalyst-cli"
      - catalyst --version
      - echo "Deploying"
      - catalyst deploy --only functions
      - echo "Deployed"
    notify:
      on-start:
        notify-type: email
        notify-variables:
          to: nishanthan.r@chakraa.io
      on-end:
        notify-type: email
        notify-variables:
          to: nishanthan.r@chakraa.io
stages:
  - name: build
    jobs:
      - catalyst-cli-setup
