version: 1
jobs:
  catalyst-cli-setup:
    steps:
      - npm install -g zcatalyst-cli
      - catalyst --version
      - echo "Its working"
stages:
  - name: build
    jobs:
      - catalyst-cli-setup
